/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: src/sanity/schema.json
export type Media1 = {
  image?: Media1Image
  alt?: string
}

export type Media2 = {
  image?: Media2Image
  alt?: string
}

export type SanityImageAssetReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset"
}

export type Media1Image = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "image.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  _type: "image"
}

export type Media2Image = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "media2.image.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  _type: "image"
}

export type ProjectMediaPayoff = {
  _type: "projectMediaPayoff"
  payoff: string
}

export type ProjectMediaDouble = {
  _type: "projectMediaDouble"
  variant:
    | "50-51"
    | "51-50"
    | "40-50"
    | "50-40"
    | "30-50"
    | "50-30"
    | "20-80"
    | "80-20"
  media1?: Media1
  media2?: Media2
}

export type SanityFileAssetReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset"
}

export type ProjectMediaSingle = {
  _type: "projectMediaSingle"
  variant:
    | "full-width"
    | "float-left-l"
    | "float-left-m"
    | "float-left-s"
    | "float-left-xs"
    | "float-right"
    | "float-right-m"
    | "float-right-s"
    | "float-right-xs"
  useVideo?: boolean
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: "image"
  }
  video?: {
    asset?: SanityFileAssetReference
    media?: unknown
    _type: "file"
  }
  alt?: string
}

export type Project = {
  _id: string
  _type: "project"
  _createdAt: string
  _updatedAt: string
  _rev: string
  orderRank?: string
  title?: string
  slug?: Slug
  isSelected?: boolean
  description?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: "span"
      _key: string
    }>
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote"
    listItem?: "bullet" | "number"
    markDefs?: Array<{
      href?: string
      _type: "link"
      _key: string
    }>
    level?: number
    _type: "block"
    _key: string
  }>
  year: number
  client?: string
  sector?: string
  credits?: Array<string>
  coverList?: {
    portrait?: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: "image"
    }
    landscape?: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: "image"
    }
    alt?: string
  }
  coverDetail?: {
    portrait?: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: "image"
    }
    landscape?: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: "image"
    }
    alt?: string
  }
  blocks?: Array<
    | ({
        _key: string
      } & ProjectMediaSingle)
    | ({
        _key: string
      } & ProjectMediaDouble)
    | ({
        _key: string
      } & ProjectMediaPayoff)
  >
}

export type SanityImageCrop = {
  _type: "sanity.imageCrop"
  top: number
  bottom: number
  left: number
  right: number
}

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot"
  x: number
  y: number
  height: number
  width: number
}

export type Slug = {
  _type: "slug"
  current: string
  source?: string
}

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch"
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: "sanity.imagePalette"
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions"
  height: number
  width: number
  aspectRatio: number
}

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata"
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: "sanity.fileAsset"
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData"
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: "sanity.imageAsset"
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: "geopoint"
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | Media1
  | Media2
  | SanityImageAssetReference
  | Media1Image
  | Media2Image
  | ProjectMediaPayoff
  | ProjectMediaDouble
  | SanityFileAssetReference
  | ProjectMediaSingle
  | Project
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint

// Source: src/sanity/lib/queries.ts
// Variable: PROJECTS_QUERY
// Query: *[_type == "project" && defined(slug.current) && isSelected == true]|order(orderRank asc)[0...100]{    _id,    orderRank,    title,    slug,    year,    coverList,    coverDetail  }
export type PROJECTS_QUERY_RESULT = Array<{
  _id: string
  orderRank: string | null
  title: string | null
  slug: Slug
  year: number
  coverList: {
    portrait?: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: "image"
    }
    landscape?: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: "image"
    }
    alt?: string
  } | null
  coverDetail: {
    portrait?: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: "image"
    }
    landscape?: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: "image"
    }
    alt?: string
  } | null
}>

// Source: src/sanity/lib/queries.ts
// Variable: ARCHIVE_PROJECTS_QUERY
// Query: *[_type == "project" && defined(slug.current)]|order(orderRank asc)[0...100]{    _id,    orderRank,    title,    slug,    year,    coverList,    coverDetail  }
export type ARCHIVE_PROJECTS_QUERY_RESULT = Array<{
  _id: string
  orderRank: string | null
  title: string | null
  slug: Slug
  year: number
  coverList: {
    portrait?: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: "image"
    }
    landscape?: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: "image"
    }
    alt?: string
  } | null
  coverDetail: {
    portrait?: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: "image"
    }
    landscape?: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: "image"
    }
    alt?: string
  } | null
}>

// Source: src/sanity/lib/queries.ts
// Variable: PROJECT_SLUGS_QUERY
// Query: *[_type == "project" && defined(slug.current)]{    "slug": slug.current  }
export type PROJECT_SLUGS_QUERY_RESULT = Array<{
  slug: string
}>

// Source: src/sanity/lib/queries.ts
// Variable: PROJECT_QUERY
// Query: *[_type == "project" && slug.current == $slug][0]{    _id,    orderRank,    title,    slug,    description,    year,    client,    sector,    credits,    coverDetail,    blocks[]{      _key,      _type,      payoff,      "variant": coalesce(variant, singleVariant, doubleVariant),      useVideo,      image,      alt,      "videoAsset": video.asset->{ url, mimeType, originalFilename },      media1{        image,        alt      },      media2{        image,        alt      }    },    "nextProject": coalesce(      *[_type == "project" && defined(slug.current) && orderRank > ^.orderRank]|order(orderRank asc)[0]{ "id": _id, slug, title, coverList, coverDetail, year },      *[_type == "project" && defined(slug.current)]|order(orderRank asc)[0]{ "id": _id, slug, title, coverList, coverDetail, year }    )  }
export type PROJECT_QUERY_RESULT = {
  _id: string
  orderRank: string | null
  title: string | null
  slug: Slug | null
  description: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: "span"
      _key: string
    }>
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal"
    listItem?: "bullet" | "number"
    markDefs?: Array<{
      href?: string
      _type: "link"
      _key: string
    }>
    level?: number
    _type: "block"
    _key: string
  }> | null
  year: number
  client: string | null
  sector: string | null
  credits: Array<string> | null
  coverDetail: {
    portrait?: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: "image"
    }
    landscape?: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: "image"
    }
    alt?: string
  } | null
  blocks: Array<
    | {
        _key: string
        _type: "projectMediaDouble"
        payoff: null
        variant:
          | "20-80"
          | "30-50"
          | "40-50"
          | "50-30"
          | "50-40"
          | "50-51"
          | "51-50"
          | "80-20"
        useVideo: null
        image: null
        alt: null
        videoAsset: null
        media1: {
          image: Media1Image | null
          alt: string | null
        } | null
        media2: {
          image: Media2Image | null
          alt: string | null
        } | null
      }
    | {
        _key: string
        _type: "projectMediaPayoff"
        payoff: string
        variant: null
        useVideo: null
        image: null
        alt: null
        videoAsset: null
        media1: null
        media2: null
      }
    | {
        _key: string
        _type: "projectMediaSingle"
        payoff: null
        variant:
          | "float-left-l"
          | "float-left-m"
          | "float-left-s"
          | "float-left-xs"
          | "float-right-m"
          | "float-right-s"
          | "float-right-xs"
          | "float-right"
          | "full-width"
        useVideo: boolean | null
        image: {
          asset?: SanityImageAssetReference
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          _type: "image"
        } | null
        alt: string | null
        videoAsset: {
          url: string
          mimeType: string
          originalFilename: string | null
        } | null
        media1: null
        media2: null
      }
  > | null
  nextProject:
    | {
        id: string
        slug: Slug
        title: string | null
        coverList: {
          portrait?: {
            asset?: SanityImageAssetReference
            media?: unknown
            hotspot?: SanityImageHotspot
            crop?: SanityImageCrop
            _type: "image"
          }
          landscape?: {
            asset?: SanityImageAssetReference
            media?: unknown
            hotspot?: SanityImageHotspot
            crop?: SanityImageCrop
            _type: "image"
          }
          alt?: string
        } | null
        coverDetail: {
          portrait?: {
            asset?: SanityImageAssetReference
            media?: unknown
            hotspot?: SanityImageHotspot
            crop?: SanityImageCrop
            _type: "image"
          }
          landscape?: {
            asset?: SanityImageAssetReference
            media?: unknown
            hotspot?: SanityImageHotspot
            crop?: SanityImageCrop
            _type: "image"
          }
          alt?: string
        } | null
        year: number
      }
    | {
        id: string
        slug: Slug | null
        title: string | null
        coverList: {
          portrait?: {
            asset?: SanityImageAssetReference
            media?: unknown
            hotspot?: SanityImageHotspot
            crop?: SanityImageCrop
            _type: "image"
          }
          landscape?: {
            asset?: SanityImageAssetReference
            media?: unknown
            hotspot?: SanityImageHotspot
            crop?: SanityImageCrop
            _type: "image"
          }
          alt?: string
        } | null
        coverDetail: {
          portrait?: {
            asset?: SanityImageAssetReference
            media?: unknown
            hotspot?: SanityImageHotspot
            crop?: SanityImageCrop
            _type: "image"
          }
          landscape?: {
            asset?: SanityImageAssetReference
            media?: unknown
            hotspot?: SanityImageHotspot
            crop?: SanityImageCrop
            _type: "image"
          }
          alt?: string
        } | null
        year: number
      }
    | null
} | null

// Query TypeMap
import "@sanity/client"
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "project" && defined(slug.current) && isSelected == true]|order(orderRank asc)[0...100]{\n    _id,\n    orderRank,\n    title,\n    slug,\n    year,\n    coverList,\n    coverDetail\n\n  }': PROJECTS_QUERY_RESULT
    '*[_type == "project" && defined(slug.current)]|order(orderRank asc)[0...100]{\n    _id,\n    orderRank,\n    title,\n    slug,\n    year,\n    coverList,\n    coverDetail\n\n  }': ARCHIVE_PROJECTS_QUERY_RESULT
    '*[_type == "project" && defined(slug.current)]{\n    "slug": slug.current\n  }': PROJECT_SLUGS_QUERY_RESULT
    '*[_type == "project" && slug.current == $slug][0]{\n    _id,\n    orderRank,\n    title,\n    slug,\n    description,\n    year,\n    client,\n    sector,\n    credits,\n    coverDetail,\n    blocks[]{\n      _key,\n      _type,\n      payoff,\n      "variant": coalesce(variant, singleVariant, doubleVariant),\n      useVideo,\n      image,\n      alt,\n      "videoAsset": video.asset->{ url, mimeType, originalFilename },\n      media1{\n        image,\n        alt\n      },\n      media2{\n        image,\n        alt\n      }\n    },\n    "nextProject": coalesce(\n      *[_type == "project" && defined(slug.current) && orderRank > ^.orderRank]|order(orderRank asc)[0]{ "id": _id, slug, title, coverList, coverDetail, year },\n      *[_type == "project" && defined(slug.current)]|order(orderRank asc)[0]{ "id": _id, slug, title, coverList, coverDetail, year }\n    )\n  }': PROJECT_QUERY_RESULT
  }
}
